version: "3.8"

services:
  flask_app:
    build: .  # Build the Flask app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:domino@db:5432/postgres  # Use service name 'db' for PostgreSQL
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: domino
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Run init.sql on startup

  selenium:
    image: selenium/standalone-chrome:4.1.0
    ports:
      - "4444:4444"
    depends_on:
      - flask_app
    volumes:
      - /dev/shm:/dev/shm

  test:
    build:
      context: .
      dockerfile: Dockerfile.test  # Specify the test Dockerfile
    depends_on:
      - flask_app
      - selenium
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:domino@db:5432/test_db
    volumes:
      - .:/app

volumes:
  postgres_data: