version: "3.8"  # Use a more recent version

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:domino@db:5432/postgres  # Use service name 'db' for PostgreSQL
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: domino
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Run init.sql on startup

volumes:
  postgres_data:

