# Usa imagen python
FROM python:3.9-slim

# asigna directorio para app
WORKDIR /app

# Copia contenido de requerimientos.txt
COPY requirements.txt ./

# Instala las dependencias especificadas en el paso anterior
RUN pip install --no-cache-dir -r requirements.txt

# Copia el contenido de la aplicacion al container
COPY . .

# Corre comando iniciar
CMD ["pytest"]